name: Push Docker Image to ECR

on:
  push:
    branches:
      - main
    paths:
      - 'Docker/**'
      - 'app/**'
      - '.github/workflows/Push-Docker-Image-To-ECR.yml'

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  ECR_REPOSITORY: threatlens

jobs:
  push-image:
    name: Build, Scan and Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::113462084471:role/threatlens-github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build \
            -f Docker/Dockerfile \
            -t $REGISTRY/${{ env.ECR_REPOSITORY }}:${{ github.sha }} \
            .

          docker tag \
            $REGISTRY/${{ env.ECR_REPOSITORY }}:${{ github.sha }} \
            $REGISTRY/${{ env.ECR_REPOSITORY }}:latest

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          format: table
          exit-code: 0
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Push image with commit SHA
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push \
            $REGISTRY/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Push latest image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push \
            $REGISTRY/${{ env.ECR_REPOSITORY }}:latest